name: BIF Toy Store CD Pipeline

on:
  workflow_dispatch:
    inputs:
      version:
        description: "App Version"
        required: true

jobs:
  build-and-package:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup .NET 10
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore & Publish
        run: |
          dotnet restore src/BIF-Toy-Store.slnx
          dotnet publish src/BIF.ToyStore.WinUI/BIF.ToyStore.WinUI.csproj `
            -c Release `
            -r win-x64 `
            --no-restore `
            /p:WindowsPackageType=None `
            /p:AppxPackage=false `
            /p:SelfContained=true `
            -o "${{ github.workspace }}\TempBuild"

      - name: Setup Obfuscar
        run: dotnet tool install --global Obfuscar.GlobalTool

      - name: Pre-process Obfuscar Config
        shell: pwsh
        run: |
          $xmlPath = "src/obfuscar.xml"
          $publishPath = "${{ github.workspace }}\TempBuild"
          (Get-Content $xmlPath).Replace("PROJECT_PATH_PLACEHOLDER", $publishPath) | Set-Content $xmlPath
          Write-Host "InPath updated to: $publishPath"

      - name: Run Obfuscation
        run: obfuscar.console src/obfuscar.xml

      - name: Finalize Build
        shell: pwsh
        run: |
          Copy-Item "${{ github.workspace }}\TempBuild\Obfuscated\*.dll" -Destination "${{ github.workspace }}\TempBuild" -Force
          Remove-Item "${{ github.workspace }}\TempBuild\Obfuscated" -Recurse

      - name: Create Release Zip
        shell: pwsh
        run: Compress-Archive -Path "TempBuild\*" -DestinationPath "BIF-ToyStore-v${{ github.event.inputs.version }}.zip"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.event.inputs.version }}
          files: BIF-ToyStore-v${{ github.event.inputs.version }}.zip
